### ISSUE TITLE
great script

### ISSUE THREAD

**Issue by sukeyisme** [axzxc1236/SharepointDownloader#1]
But why awlay redownload the same file many times.

**Comment by axzxc1236** [comment]
Did you encountered a scenario where it attempts to re-download a file many times?

Strange...... it should check the disk before attempting to download, at least I programmed it to do that.

What is the operating system you run the script on? I didn't test much on non-Windows 10 systems.

Does the corresponding file written to the folder you specified? Is there .aria2 file there? (In the case .aria2 file exists, it means aria2 didn't download the file completely, like disconnect from Sharepoint server when downloading)

Does this happen on a specific file name? (like only happens if the file name ends with .xxx)

**Comment by sukeyisme** [comment]
I use it in docker container(linux). I found it 100% downloaded but the aria2 file is still exist.

**Comment by axzxc1236** [comment]
Can you use [AriaNg](https://ariang.mayswind.net/latest/) to connect to your Aria2 server and verify that Aria2 marks download as 100%?

**Comment by sukeyisme** [comment]
Yes.I confirm.

佴弌 <notifications@github.com> 于 2020年6月1日周一 18:37写道：

**Comment by axzxc1236** [comment]
Hmm..... So I think it's a problem with Aria2, not this script, somehow it fails to cleanup .aria2 file.

I would suggest doing these things:

1. Check the output of aria2 process, does it show something important in there?

2. Adjust `log-level` in aria2.conf, the other options are `debug`, `notice`, `warn` or `error` and re-download the file to debug.

3. or set `continue` in aria2.conf to `false` and restart aria2, it shouldn't create more .aria2 file then. (But doing this will remove the function to resume download progress)

**Comment by axzxc1236** [comment]
I want to ask a question, does the file in question happens to be a very small file? (<1024 bytes)

If so, the problem might have to do with https://github.com/axzxc1236/SharepointDownloader/blob/master/index.js#L401 to https://github.com/axzxc1236/SharepointDownloader/blob/master/index.js#L408

**Comment by sukeyisme** [comment]
No,big file.4-5G.


佴弌 <notifications@github.com> 于 2020年6月1日周一 19:01写道：

**Comment by axzxc1236** [comment]
Do you have time to follow [instructions I gave few days ago](https://github.com/axzxc1236/SharepointDownloader/issues/1#issuecomment-636782074) to try to find what's wrong with Aria2?

If you still can't find out what's wrong, I suggest you can add your own code to remove .aria2 file [before line 342](https://github.com/axzxc1236/SharepointDownloader/blob/master/index.js#L342), I won't add the code to do this because Aria2 should remove that file by itself.

**Comment by sukeyisme** [comment]
ok, i will try.

**Comment by sukeyisme** [comment]
I check the log from you script,it always say downloaded errored,then readd the task.But the file is completed downloaded.

**Comment by sukeyisme** [comment]
[HttpResponse.cc:86] errorCode=8 Invalid range header.

**Comment by sukeyisme** [comment]
And do you have add all task in the list  to download while one task error occured?

**Comment by axzxc1236** [comment]
Is it possible for you to share whatever Sharepoint link you are trying to download?

I tried downloading some files and I can't reproduce the error code you mentioned.

**Comment by sukeyisme** [comment]
Any other contact way？

**Comment by sukeyisme** [comment]
What aria2 version do you use?

**Comment by axzxc1236** [comment]
aria2 1.35.0, compiled from source

You can send a email to <redacted>

**Comment by sukeyisme** [comment]
Sended.

**Comment by axzxc1236** [comment]
Sorry, I can't reproduce the error.

I downloaded the whole thing **on my Linux system** just fine.

**Comment by axzxc1236** [comment]
My suggestion is

(1) try deleting the downloaded file that gives you problem and try download it again.

(2) report this issue to Aria2.

**Comment by sukeyisme** [comment]
Ok, but i think you sloud not readd task if already exist error. Will be infinite loop.

**Comment by axzxc1236** [comment]
I programmed it that way because Sharepoint just straight up blocks downloads when there are too many downloads, even disconnecting ongoing downloads.

This might sounds stupid but it works as intended, it retries on failures.

**Comment by sukeyisme** [comment]
Now OK.Thank you.
